backbone:
  # [from, module, args]
  - [-1, StemBlock, [16, 16, True]] # 0-P2/4
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']] # 1-P2/4
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']] # 2-P3/8
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]  # 3-P4/16
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']] # 4-P5/32

# 640x640x3
# 320x320x64

encoder:
  - [1, ConvNormLayer_fuse, [128, 1, 1]] # 5-P2/4
  - [2, ConvNormLayer_fuse, [128, 1, 1]] # 6-P3/8
  - [3, ConvNormLayer_fuse, [128, 1, 1]] # 7-P4/16
  - [4, ConvNormLayer_fuse, [256, 1, 1]] # 7-P4/16

  - [-1, TransformerEncoderBlock, [8, 1024, 0.1, "relu", 10000, False]] # 8-P4/16
  - [-1, ConvNormLayer_fuse, [128, 1, 1]] # 9
  - [[7, -1], CAF, [128]] # 10-P4/16
  - [-1, RepNCSPELAN4, [128, 256, 61, 1, False, 'silu']] # 12-P4/16

  - [-1, ConvNormLayer_fuse, [128, 1, 1]] # 9
  - [[6, -1], CAF, [128]] # 10-P4/16
  - [-1, RepNCSPELAN4, [128, 256, 61, 1, False, 'silu']] # 12-P4/16

  - [-1, ConvNormLayer_fuse, [128, 1, 1]] # 13
  - [[5, -1], CAF, [256]] # 10-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 61, 1, False, 'silu']] # 12-P4/16

  - [[16, -1], CAF_Down, [256]] # 17-P5/32
  - [-1, RepNCSPELAN4, [256, 512, 61, 1, False, 'silu']] # 12-P4/16

  - [[13, -1], CAF_Down, [256]] # 17-P5/32
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 12-P4/16
decoder:
  - [[18,20,22], DFINETransformer, {"feat_strides":[4,8,16], "hidden_dim": 256, "num_levels": 3, "num_layers": 3, "num_points": [3,6,6], "dim_feedforward": 1024}]