task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/visdrone/train2017
    ann_file: /root/autodl-tmp/visdrone/annotations/instances_train2017.json
    # img_folder: /datasets/MoGuiMianJu/visdrone/VisDrone2019-DET-train/images
    # ann_file: /datasets/MoGuiMianJu/visdrone/VisDrone2019-DET-train/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/visdrone/val2017
    ann_file: /root/autodl-tmp/visdrone/annotations/instances_val2017.json
    # img_folder: /datasets/MoGuiMianJu/visdrone/VisDrone2019-DET-val/images
    # ann_file: /datasets/MoGuiMianJu/visdrone/VisDrone2019-DET-val/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction

# val_dataloader:
#   type: DataLoader
#   dataset:
#     type: CocoDetection
#     img_folder: /root/autodl-tmp/visdrone/test2017
#     ann_file: /root/autodl-tmp/visdrone/annotations/instances_test2017.json
#     return_masks: False
#     transforms:
#       type: Compose
#       ops: ~
#   shuffle: False
#   num_workers: 4
#   drop_last: False
#   pin_memory: True
#   collate_fn:
#     type: BatchImageCollateFunction